title: 橡树工作室
description: 助力品牌出海
baseurl: ""  
url: "https://adrwei.github.io"

# 明确指定包含的插件
plugins:
  - jekyll-feed

# 修正默认布局配置
defaults:
  - scope:
      path: ""       # 所有文件
      type: pages    # 明确指定页面类型
    values:
      layout: default
