title: 橡树工作室
description: 助力品牌出海
baseurl: ""
url: "https://adrwei.github.io"

# 插件配置
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from

# 默认布局设置
defaults:
  - scope:
      path: ""
    values:
      layout: default

# 集合配置
collections:
  pages:
    output: true
    permalink: /:path/

# 需要特别保留的HTML文件
include:
  - CNAME
  - .nojekyll
