name: Build Articles to Posts
on: 
  workflow_dispatch:  # 允许手动触发

jobs:
  convert-md:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        sudo apt-get install -y pandoc
        mkdir -p posts

    - name: Process Markdown files
      run: |
        for file in articles/*.md; do
          filename=$(basename "$file" .md)
          
          # 安全转换Markdown为HTML
          pandoc "$file" -o "posts/${filename}.tmp.html" -t html
          
          # 使用awk处理模板替换（更安全的方式）
          awk -v content="$(cat posts/${filename}.tmp.html)" '
            BEGIN { RS="^$"; ORS="" }
            { gsub("{{CONTENT}}", content); print }
          ' .github/templates/blog-template.html > "posts/${filename}.html"
          
          rm "posts/${filename}.tmp.html"
        done

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add posts/
        git commit -m "Auto-generated HTML from articles [skip ci]" || echo "No changes to commit"
        git push
